/* SPDX-License-Identifier: Apache-2.0 */
/* Compile the real hardware MIDI parser with a deterministic clock and a
 * mocked voice engine. OF_PC would test only the SDK's no-op implementation.
 * Suppress just the RISC-V timer/service accessors and memory attributes. */
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define OF_TIMER_H
#define OF_SERVICES_H
#define OF_FASTRAM_H
#define OF_FASTDATA
static uint32_t clock_us;
static uint32_t of_time_us(void) { return clock_us; }
static void (*timer_callback)(void);
static void of_timer_set_callback(void (*cb)(void), uint32_t hz) {
    (void)hz;
    timer_callback = cb;
}
static const struct { uint32_t (*timer_get_us)(void); } test_svc = {of_time_us};
#define OF_SVC (&test_svc)
#include MIDI_SOURCE

static ofsf_header_t bank;
static unsigned event_cost, tick_cost, ticks, all_offs;
static unsigned notes[16];
static uint32_t note_time[16];
int of_smp_bank_bind_preloaded(void) { return 0; }
const ofsf_header_t *of_smp_bank_get(void) { return &bank; }
const void *of_smp_bank_sample_base(void) { return &bank; }
int of_smp_zone_lookup(int b, int p, int k, int v,
                      const ofsf_zone_t **z, int n) {
    (void)b; (void)p; (void)k; (void)v; (void)z; (void)n;
    return 0;
}
void smp_voice_init(void) {}
int smp_voice_note_on(const ofsf_zone_t *z, int c, int n, int v, const void *b) {
    (void)z; (void)c; (void)n; (void)v; (void)b;
    return 0;
}
void smp_voice_note_off(int c, int n) {
    (void)n;
    notes[c]++;
    note_time[c] = clock_us;
}
void smp_voice_tick(void) {
    ticks++;
    clock_us += tick_cost;
    tick_cost = 0;
}
void smp_voice_tick_record_pump(uint32_t e, int t, int b) {
    (void)e; (void)t; (void)b;
}
void smp_voice_update_pan(int c, int p) {
    (void)c; (void)p;
    clock_us += event_cost;
    event_cost = 0;
}
#define STUB1(name) void name(int a) { (void)a; }
#define STUB2(name) void name(int a, int b) { (void)a; (void)b; }
#define STUB3(name) void name(int a, int b, int c) { (void)a; (void)b; (void)c; }
STUB1(smp_voice_set_master_volume)
STUB1(smp_voice_all_off)
STUB2(smp_voice_update_bend)
STUB2(smp_voice_update_mod)
STUB2(smp_voice_update_sustain)
STUB2(smp_voice_update_reverb_send)
STUB2(smp_voice_update_chorus_send)
STUB3(smp_voice_update_volume)
STUB3(smp_voice_update_filter)
void smp_voice_all_off_global(void) { all_offs++; }

static uint8_t song[256];
static size_t song_len;
static void append(const uint8_t *p, size_t n) {
    assert(song_len + n <= sizeof(song));
    memcpy(song + song_len, p, n);
    song_len += n;
}
static void add_track(const uint8_t *p, size_t n) {
    assert(n < 256);
    const uint8_t header[] = {'M','T','r','k',0,0,0,(uint8_t)n};
    append(header, sizeof(header));
    append(p, n);
}
static void start_song(int tracks, int loop, uint32_t start) {
    clock_us = start;
    ticks = all_offs = event_cost = tick_cost = 0;
    memset(notes, 0, sizeof(notes));
    /* 500 ticks/beat at 500000 us/beat: each delta tick is exactly 1 ms. */
    song[9] = tracks > 1 ? 1 : 0;
    song[11] = tracks;
    assert(of_midi_init() == OF_MIDI_OK);
    assert(of_midi_play(song, song_len, loop) == OF_MIDI_OK);
    assert(timer_callback == of_midi_pump);
}
static void header(void) {
    const uint8_t h[] = {'M','T','h','d',0,0,0,6,0,1,0,2,1,244};
    song_len = 0;
    append(h, sizeof(h));
}
static void pump_at(uint32_t now) {
    clock_us = now;
    assert(timer_callback);
    timer_callback();
}

static void test_track_deadline(unsigned event_delay, unsigned tick_delay,
                                uint32_t start) {
    /* First track has work at 1 ms. Second track's note is due at 4 ms.
     * An expensive first event OR envelope tick exhausts the pump budget,
     * but must not move the second track's absolute deadline. */
    const uint8_t a[] = {1,0xb0,10,64,100,0xff,0x2f,0};
    const uint8_t b[] = {4,0x81,60,0,100,0xff,0x2f,0};
    header();
    add_track(a, sizeof(a));
    add_track(b, sizeof(b));
    start_song(2, 0, start);
    event_cost = event_delay;
    tick_cost = tick_delay;
    pump_at(start + 1000);
    assert(notes[1] == 0);
    pump_at(start + 4000);
    if (notes[1] != 1 || note_time[1] != start + 4000) {
        fprintf(stderr, "FAIL: track 1 missed its 4 ms deadline "
                "(event cost=%u, tick cost=%u, clock start=%u)\n",
                event_delay, tick_delay, start);
        assert(notes[1] == 1 && note_time[1] == start + 4000);
    }
    of_midi_stop();
    assert(!timer_callback);
}

static void test_single_track(void) {
    /* Format 0 as generated by DOOM: same-time events, running status,
     * note-off timing and end-of-track remain unchanged. */
    const uint8_t a[] = {1,0xc0,12,0,13,3,0x80,60,0,1,0xff,0x2f,0};
    header();
    add_track(a, sizeof(a));
    start_song(1, 0, 0);
    pump_at(500);
    assert(of_midi_get_program(0) == 0 && ticks == 0);
    pump_at(1000);
    assert(of_midi_get_program(0) == 13 && ticks == 1);
    pump_at(3999);
    assert(notes[0] == 0);
    pump_at(4000);
    assert(notes[0] == 1 && note_time[0] == 4000);
    pump_at(5000);
    pump_at(6000);
    assert(!of_midi_playing());
    of_midi_stop();
}

static void test_pause_and_loop(void) {
    const uint8_t a[] = {1,0x80,60,0,1,0xff,0x2f,0};
    header();
    add_track(a, sizeof(a));
    start_song(1, 1, 0);
    of_midi_pause();
    pump_at(1000000);
    assert(notes[0] == 0 && ticks == 0);
    of_midi_resume();
    pump_at(1001000);
    assert(notes[0] == 1);
    pump_at(1002000);
    pump_at(1003000);
    assert(of_midi_playing() && all_offs == 2);
    pump_at(1004000);
    assert(notes[0] == 2);
    of_midi_stop();
}

int main(void) {
    test_single_track();
    test_pause_and_loop();
    test_track_deadline(0, 0, 0);
    test_track_deadline(2500, 0, 0);
    test_track_deadline(0, 2500, 0);
    test_track_deadline(2500, 0, UINT32_MAX - 2000);
    puts("PASS: MIDI scheduling, event/envelope overruns, clock wrap, pause and loop");
    return 0;
}
